module.exports = {
  apps: [
    {
      name: 'api_gateway',
      cwd: './backend/api_gateway',
      script: 'node',
      args: 'dist/app.js',
      env: { PORT: 3001, START_DELAY: 0 },
      autorestart: true,
      watch: false,
    },
    {
      name: 'billing_service',
      cwd: './backend/billing_service',
      script: 'node',
      args: 'dist/app.js',
      env: { PORT: 3004, START_DELAY: 3000 },
      autorestart: true,
      watch: false,
    },
    {
      name: 'crm_service',
      cwd: './backend/crm_service',
      script: 'node',
      args: 'dist/app.js',
      env: { PORT: 3005, START_DELAY: 9000 },
      autorestart: true,
      watch: false,
    },
    {
      name: 'employee_service',
      cwd: './backend/employee_service',
      script: 'node',
      args: 'dist/app.js',
      env: { PORT: 3002, START_DELAY: 6000 },
      autorestart: true,
      watch: false,
    },
    {
      name: 'ven_inv_service',
      cwd: './backend/ven_inv_service',
      script: 'node',
      args: 'dist/app.js',
      env: { PORT: 3003, START_DELAY: 12000 },
      autorestart: true,
      watch: false,
    },
    {
      name: 'frontend',
      cwd: './frontend',
      script: 'node',
      args: 'start.js',
      env: { PORT: 3000, START_DELAY: 15000 },
      autorestart: true,
      watch: false,
    },
  ],
};
