export enum InvoiceStatus {
  // Template lifecycle
  TEMPLATE = 'TEMPLATE',
  ASSIGNED = 'ASSIGNED',

  // Quotation lifecycle
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  CUSTOMER_ACCEPTED = 'CUSTOMER_ACCEPTED',
  CUSTOMER_REJECTED = 'CUSTOMER_REJECTED',
  EMPLOYEE_APPROVED = 'EMPLOYEE_APPROVED',
  WAITING_FINANCE_APPROVAL = 'WAITING_FINANCE_APPROVAL',
  FINANCE_APPROVED = 'FINANCE_APPROVED',
  FINANCE_REJECTED = 'FINANCE_REJECTED',

  // Contract lifecycle
  ACTIVE_CONTRACT = 'ACTIVE_CONTRACT',
  INVOICED = 'INVOICED',
  PAID = 'PAID',

  // Terminal states
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  RETAKEN = 'RETAKEN',
  SUPERSEDED = 'SUPERSEDED',
}
