name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - test

  push:
    branches:
      - test
      - nadhil

jobs:
  build:
    name: Build Xerocare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.26.0
          run_install: false

      - name: Install Dependencies
        run: HUSKY=0 pnpm install --frozen-lockfile

      - name: Type Check
        run: pnpm run typecheck

      - name: Build Backend Services
        run: |
          cd backend/employee_service && pnpm run build && cd ../..
          cd backend/api_gateway && pnpm run build && cd ../..
          cd backend/billing_service && pnpm run build && cd ../..
          cd backend/crm_service && pnpm run build && cd ../..
          cd backend/ven_inv_service && pnpm run build && cd ../..

      - name: Build Frontend
        run: cd frontend && NODE_OPTIONS="--max-old-space-size=3072" pnpm run build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:3001
